### PR TITLE
Add self to rustasync

### PR DESCRIPTION
**Pull request by JohnTitor**
## Description

Add self to rustasync, I'd like to work on this project!

r? @cramertj @yoshuawuyts @Nemo157

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by JohnTitor** [comment]
@cramertj Sorry to bother you but could you invite me to the organization? I'd like to merge some minor PRs.

**Comment by JohnTitor** [comment]
https://github.com/rustasync/.github/pull/2 and https://github.com/rustasync/areweasyncyet.rs/pull/24. The first one may resolve confusing.

**Comment by JohnTitor** [comment]
Thanks, @secretfader! 
And I'm a bit confused because I'm not sure the difference from the people who have been invited to the organization by submitting a PR to add to the roster.

**Comment by Nemo157** [comment]
Would be good to bring this up tomorrow at the meeting, I feel like we should be adding everyone who's in the list as a member of the organization so they can be assigned tickets, requested for review, etc. (which might mean the owners specifically should be pinged on these PRs as they're the only ones that I believe have access), but I'm not sure whether everyone should be added to the `rustasync/maintainers` team to get merge access.

**Pull request merged**
